const path = require('path');
const { loadCSVs, getAllRouters } = require('./services/dataLoader');
const { askCopilot } = require('./services/copilotService');

async function testKey() {
  try {
    loadCSVs(path.join(__dirname, '../data'));
    const routers = getAllRouters();
    const routerId = routers[0]?.router_id || 'RTR-001';
    console.log(`Testing AI Diagnostic Copilot with ${routerId}...`);
    const result = await askCopilot(routerId, `Why is router ${routerId} performing badly?`);
    console.log("\n==================== AI DIAGNOSTIC RESULT ====================");
    console.log("Router ID:     ", result.router_id);
    console.log("Health Score:  ", result.health_score);
    console.log("Generated By:  ", result.generatedBy);
    console.log("Fix Type:      ", result.fixType);
    console.log("Recommended Fix:", result.recommendedFix);
    console.log("Diagnosis:     ", result.diagnosis);
    console.log("Evidence:      ", result.evidence);
    console.log("==============================================================\n");
  } catch (err) {
    console.error("Diagnostic error:", err);
  }
}

testKey();
